# Generated by Django 3.0.5 on 2020-04-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('vendor_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_vat_rate', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('full_price_amount', models.FloatField()),
                ('discounted_amount', models.FloatField()),
                ('vat_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('orders', models.ManyToManyField(through='shop.OrderLine', to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCommissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vendor_id', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(through='shop.ProductPromotion', to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(through='shop.ProductPromotion', to='shop.Promotion'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.OrderLine', to='shop.Product'),
        ),
    ]
